config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include("resume.me.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

resume/me/urls.py
"""Me app URL config"""

from django.urls import path

from . import views

app_name = "me"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("<str:username>", views.ProfileView.as_view(), name="profile"),
]

resume/me/models.py
"""Me app models"""

from django.contrib.auth import get_user_model
from django.db import models
from model_utils.models import TimeStampedModel

User = get_user_model()


class ProgrammingLanguage(TimeStampedModel):
    """Programming language model"""

    PYTHON = 0
    JAVASCRIPT = 1
    JAVA = 2
    C = 3
    CPP = 4
    CSHARP = 5
    PHP = 6
    GO = 7
    RUST = 8
    DART = 9
    ELIXIR = 10
    NAME_CHOICES = [
        (PYTHON, "Python"),
        (JAVASCRIPT, "JavaScript"),
        (JAVA, "Java"),
        (C, "C"),
        (CPP, "C++"),
        (CSHARP, "C#"),
        (PHP, "PHP"),
        (GO, "Go"),
        (RUST, "Rust"),
        (DART, "Dart"),
        (ELIXIR, "Elixir"),
    ]
    name = models.PositiveSmallIntegerField(choices=NAME_CHOICES)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.get_name_display()} - @{self.user.username}"

resume/me/views.py
"""Me app views"""

from typing import Any

from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

User = get_user_model()


class HomeView(TemplateView):
    """Home view"""

    template_name = "me/home.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["users"] = User.objects.all()
        return context


class ProfileView(TemplateView):
    """Profile view"""

    template_name = "me/profile.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        username = self.kwargs.get("username")
        user = get_object_or_404(User, username=username)
        context["user"] = user
        context["languages"] = user.programminglanguage_set.all()
        return context

resume/templates/base.html
{% load static i18n %}<!doctype html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Mi Portafolio{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Mi CV">
    <meta name="author" content="Mauricio Chávez Olea">

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <script defer src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </head>

  <body>
    {% block content %}{% endblock content %}
    {% block modal %}{% endblock modal %}
    {% block inline_javascript %}{% endblock inline_javascript %}
  </body>
</html>

resume/templates/me/home.html
{% extends "base.html" %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Usuarios</h1>
    <div class="content">
      {% for user in users %}
      <p>
        <a href="{% url 'me:profile' user.username %}">@{{ user.username }}</a>
      </p>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}

resume/templates/me/profile.html
{% extends 'base.html' %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Perfil de @{{ user.username }}</h1>
    <div class="content">
      <h4>Lenguajes de programación</h4>
      <ul>
        {% for language in languages %}
        <li>{{ language.get_name_display }}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
</section>
{% endblock content %}